### ISSUE TITLE
Not working in fragment

### ISSUE THREAD

**Issue by csj5483** [Dhaval2404/ImagePicker#165]

**Comment by hitesh-dhamshaniya** [comment]
Hello @csj5483,
Kindly check the sample application in which they have demonstrated how to used Fragment.
And If you still having an issue to use it in a fragment, describe your scenario in details with device and OS details.
Thank you.

**Comment by Dhaval2404** [comment]
@tobiasKaminsky If you're starting the ImagePicker from Fragment, instead of getActivity() you need to pass fragment instance.

```kotlin
ImagePicker.with(getActivity()) // Wrong, Should not use getActivity() inside fragment
 .start();
```

```kotlin
ImagePicker.with(this) // Correct, Where "this" is fragment instance
 .start();
```

In ImagePicker, Two methods are available:
1. with(activity: Activity)
2. with(fragment: Fragment)

I believe you're using "**with(activity: Activity)**" inside the fragment, while you should use **with(fragment: Fragment)**.

Hope this answered your question. Please let me know if you're still facing the issue

![image](https://user-images.githubusercontent.com/7314181/118350573-2adf2400-b575-11eb-8c06-074577a98408.png)
