### ISSUE TITLE
onActivityResult is not called

### ISSUE THREAD

**Issue by tobiasKaminsky** [Dhaval2404/ImagePicker#181]
I start the image picker with:
```
ImagePicker.Companion.with(getActivity())
.start();
```

I can successfully select an image, but onActivityResult(…) in same Activity is not called.

When I use 
```
 Intent action = new Intent(Intent.ACTION_OPEN_DOCUMENT);
            action.setType("image/*");
            action.addCategory(Intent.CATEGORY_OPENABLE);

        startActivityForResult(Intent.createChooser(action, getActivity().getResources().getString(
                R.string.chooseImage)), 1);
```

I do get an result back.

There is not much in Logcat.
I am using ButterKnifeController which encapsulates activity.

**Comment by tobiasKaminsky** [comment]
It seems that the problem is "who" is calling startActivityForResult(…).

In my case this must be done via the Controller, and not via activity.

Switching
```
startActivityForResult(Intent.createChooser(action, getActivity().getResources().getString(
                R.string.chooseImage)), 1);
```
to 
```
getActivity().startActivityForResult(Intent.createChooser(action, getActivity().getResources().getString(
                R.string.chooseImage)), 1);
```
results in the same problem.

**Comment by Firas-El-Mohtar** [comment]
I am facing the exact same issue, it worked for a few days but then suddenly stopped. Any solutions?

**Comment by Dhaval2404** [comment]
@tobiasKaminsky If you're starting the ImagePicker from Fragment, instead of getActivity() you need to pass fragment instance.

ImagePicker.Companion.with(this)
.start();

In ImagePicker, Two methods are available:
1. with(activity: Activity)
2. with(fragment: Fragment)

I believe you're using "**with(activity: Activity)**" inside the fragment, while you should use **with(fragment: Fragment)**.

Hope this answered your question. Please let me know if you're still facing the issue

![image](https://user-images.githubusercontent.com/7314181/118350573-2adf2400-b575-11eb-8c06-074577a98408.png)
