### ISSUE TITLE
Android 10 permission issue

### ISSUE THREAD

**Issue by jonandersen** [Dhaval2404/ImagePicker#29]
Hi there! 

Thanks for making this great library! I ran into some issues when using the library for Android 10. It's related to the file permission and the changes that have been made to it. The latest version uses scoped permissions for data storage: https://developer.android.com/training/data-storage/files/external-scoped

I'm not 100% sure if I need to update something on the caller side or if the library needs some changes. I was able to temporarily getting the library working by adding `
android:requestLegacyExternalStorage="true"` to my manifest.

**Comment by Dhaval2404** [comment]
@jonandersen Thank you so much for the suggestions!

**Comment by jonandersen** [comment]
I think I was a little unclear above,  the library doesn't work on Android 10 unless the legacy storage is enabled.

**Comment by Dhaval2404** [comment]
@jonandersen after your comment only I got to know that it's not working in android 10. For now, I will add your comment inside readme file for anyone who is facing this issue.

In the upcoming days, I will add support for android 10.

Thank you so much!

**Comment by JarnoVgr** [comment]
Any update on the support of Android 10 and higher?

Please note that scoped storage will most likely be mandatory on Android 11.

**Comment by Dhaval2404** [comment]
@JarnoVgr I'm planning to release it with v1.8. So It may take time(About a month). Currently, I'm working on v1.7.

**Comment by Dhaval2404** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Android 11 Scope Storage Support #29](https://trello.com/c/zOFKveQp/12-android-11-scope-storage-support-29)

**Comment by cepero91** [comment]
thanks, I'm also facing with this issue

**Comment by chandmohd** [comment]
Any Update on android 10 or higher ?
Your apis never return to onActivityResult(...) after taking picture 
I have enables `android:requestLegacyExternalStorage="true"` but does not work

**Comment by ThanosFisherman** [comment]
`android:requestLegacyExternalStorage="true"` won't work anymore from Android 11 and above see [here](https://stackoverflow.com/questions/63364476/requestlegacyexternalstorage-is-not-working-in-android-11-api-30)

**Comment by sinhpn92** [comment]
I have got permission not allowed on Android 11. I did check that it's approved, But the lib still return false. Have anyone facing this error?

**Comment by galvandamiancarlos** [comment]
any solution?

**Comment by costular** [comment]
Any update on this?

**Comment by vishalkumarsinghvi** [comment]
We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy-friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.
Any changes we have to that. @Dhaval2404 Because after 5 may 2021 our apps will remove from play store and we cannot publish again

**Comment by Achozen** [comment]
Any update regarding **requestLegacyExternalStorage** usage for Android 11? Can we expect any solution before the 5'th of May or we need to switch to another library?

**Comment by vishalkumarsinghvi** [comment]
@Dhaval2404  without READ_EXTERNAL_STORAGE && WRITE_EXTERNAL_STORAGE  permission can we read images from android or not  like so many people are using Intents without permission they are able to pick images.
